### ISSUE TITLE
WARNING: bytestring is deprecated

### ISSUE THREAD

**Issue by juliohm** [spencerlyon2/PlotlyJS.jl#103]
>WARNING: bytestring(s::AbstractString...) is deprecated, use string(s...) instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in bytestring(::String) at ./deprecated.jl:50
 in handle_new_from_data(::String, ::Gtk.GLib.GError) at /home/juliohm/.julia/v0.5/Rsvg/src/calls.jl:61
 in handle_new_from_data(::String) at /home/juliohm/.julia/v0.5/Rsvg/src/calls.jl:69
 in #savefig#175(::Symbol, ::Function, ::PlotlyJS.SyncPlot{PlotlyJS.ElectronDisplay}, ::String) at /home/juliohm/.julia/v0.5/PlotlyJS/src/savefig.jl:164
 in savefig(::PlotlyJS.SyncPlot{PlotlyJS.ElectronDisplay}, ::String) at /home/juliohm/.julia/v0.5/PlotlyJS/src/savefig.jl:106
 in #savefig#184(::Array{Any,1}, ::Function, ::PlotlyJS.SyncPlot{PlotlyJS.JupyterDisplay}, ::String, ::Vararg{String,N}) at /home/juliohm/.julia/v0.5/PlotlyJS/src/savefig.jl:204
 in savefig(::PlotlyJS.SyncPlot{PlotlyJS.JupyterDisplay}, ::String) at /home/juliohm/.julia/v0.5/PlotlyJS/src/savefig.jl:204
 in plotlyjs_save_hack at /home/juliohm/.julia/v0.5/Plots/src/backends/plotlyjs.jl:98 [inlined]
 in _show at /home/juliohm/.julia/v0.5/Plots/src/backends/plotlyjs.jl:101 [inlined]
 in show(::IOStream, ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.PlotlyJSBackend}) at /home/juliohm/.julia/v0.5/Plots/src/output.jl:196
 in png(::Plots.Plot{Plots.PlotlyJSBackend}, ::String) at /home/juliohm/.julia/v0.5/Plots/src/output.jl:8
 in savefig(::Plots.Plot{Plots.PlotlyJSBackend}, ::String) at /home/juliohm/.julia/v0.5/Plots/src/output.jl:116
 in macro expansion; at ./In[2]:16 [inlined]
 in anonymous at ./<missing>:?
 in include_string(::String, ::String) at ./loading.jl:441
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/juliohm/.julia/v0.5/IJulia/src/execute_request.jl:175
 in eventloop(::ZMQ.Socket) at /home/juliohm/.julia/v0.5/IJulia/src/eventloop.jl:8
 in (::IJulia.##13#19)() at ./task.jl:360
while loading In[2], in expression starting on line 4

**Comment by spencerlyon2** [comment]
Thanks @juliohm for bringing this up.

The third line of the traceback (first line that isn't in base julia) says

```
in handle_new_from_data(::String, ::Gtk.GLib.GError) at /home/juliohm/.julia/v0.5/Rsvg/src/calls.jl:61
```

indicating that the problem is in the Rsvg package. I'm going to close here as there is nothing we to do inside PlotlyJS.jl, but I recommend opening an issue (or better yet, a pull request) over in [Rsvg.jl](https://github.com/lobingera/Rsvg.jl)
