### ISSUE TITLE
Plotting a 3D surface with facecolor different from its height values

### ISSUE THREAD

**Issue by BoundaryValueProblems** [spencerlyon2/PlotlyJS.jl#104]
I really want to use ```surface``` function to plot a 3D surface with the surface color specified not by the height (z) matrix, but some other matrix. For example, imagine a temperature distribution over a 3D topographic map. I can do this using ```PyPlot.jl``` using ```plot_surface``` function by specifying its ```facecolors``` attribute. But that attribute does not work with ```surface``` of ```PlotlyJS.jl``` although supplying it does not generate an error. What needs to be done if I want ```surface``` to have that functionality? Thanks!

**Comment by spencerlyon2** [comment]
You should be able to do this by setting the `surfacecolor` trace attribute:

```julia
plot(surface(z=z, surfacecolor=other_array))
```

Docs [here](https://plot.ly/javascript/reference/#surface-surfacecolor)

**Comment by BoundaryValueProblems** [comment]
Thanks a lot, Spencer!
