### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by rcnlee** [spencerlyon2/PlotlyJS.jl#13]
Are events (e.g., click, hover) supported at this time?

Thanks!

**Comment by spencerlyon2** [comment]
There isn't anything here that officially support events... yet. 

Could you post some julia code you would _like_ to be able to write and a quick description of what you hope it does? That'd be very helpful, thanks

**Comment by rcnlee** [comment]
Thanks for the quick reply! For example, if I had a scatter plot where I wanted to display some custom additional text on hover (or perhaps change the highlighting), would I be able to do this?  Looking at the examples here:
https://plot.ly/javascript/hover-events/
it seems that it requires callbacks, e.g., event listeners on 'plotly_hover'
However, I also see some examples of scatter plots that seem to achieve this without the event listeners.  So I'm not sure...

**Comment by spencerlyon2** [comment]
Hi @rcnlee sorry for the delay in responding this time.

So you can definitely set the text on hover by setting the `text` field of the trace. Something like this should work:

```julia
p = Plot(scatter(;x=1:10, y=rand(10), text=["Point $i" for i in 1:10]))
show(p)
```

<img width="667" alt="screen shot 2016-01-05 at 10 16 37 am" src="https://cloud.githubusercontent.com/assets/1001948/12121948/731d85b4-b395-11e5-9d62-d860664b58f9.png">

See the [chart attribute reference](https://plot.ly/javascript/reference/#scatter-text) for more details.

Regarding more advanced event based logic, I don't think we are quite there.

It might be possible to pass Julia callbacks to javascript using Blink, but I'd need expert advice from @one-more-minute to know how to do that

**Comment by rcnlee** [comment]
Thanks @spencerlyon2 !
