### ISSUE TITLE
savefig (via cairosvg) doesn't show negative signs in tick labels

### ISSUE THREAD

**Issue by spencerlyon2** [spencerlyon2/PlotlyJS.jl#14]

**Comment by datafig** [comment]
I am encountering issues creating any output with `savefig()`. I am getting the following error.

```julia
savefig(p, "test.pdf")
LoadError: Callback timed out
while loading In[3], in expression starting on line 1

 in yieldto at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in wait at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib (repeats 2 times)
 in wait at /Users/datafig/.julia/v0.4/Blink/src/rpc/callbacks.jl:8
 in js at /Users/datafig/.julia/v0.4/Blink/src/rpc/rpc.jl:28
 in to_svg at /Users/datafig/.julia/v0.4/PlotlyJS/src/api.jl:25
 in anonymous at /Users/datafig/.julia/v0.4/PlotlyJS/src/api.jl:40
 in open at iostream.jl:114
 in savefig at /Users/datafig/.julia/v0.4/PlotlyJS/src/api.jl:39
```

**Comment by spencerlyon2** [comment]
Yes, sorry about this. It is a known problem that I'm actually working on fixing right now.

I will hopefully have a fix within the next hour or so and will post here if I do.

**Comment by spencerlyon2** [comment]
Sorry, but I wasn't able to fix this tonight, but now have a pretty decent idea of what I need to do.

**Comment by spencerlyon2** [comment]
Hey @datafig this should be resolved now.

Can you pull the latest version and try `savefig`?

**Comment by datafig** [comment]
I am getting same error. I did a `Pkg.update()` verified that the changes were reflected in local copy of `api.jl`

savefig(p, "test.pdf")
LoadError: Callback timed out
while loading In[4], in expression starting on line 1

 in yieldto at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in wait at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib (repeats 2 times)
 in wait at /Users/datafig/.julia/v0.4/Blink/src/rpc/callbacks.jl:8
 in js at /Users/datafig/.julia/v0.4/Blink/src/rpc/rpc.jl:28
 in js at /Users/datafig/.julia/v0.4/PlotlyJS/src/api.jl:134
 in _img_data at /Users/datafig/.julia/v0.4/PlotlyJS/src/api.jl:119
 in savefig at /Users/datafig/.julia/v0.4/PlotlyJS/src/api.jl:64

**Comment by datafig** [comment]
I cannot find `cairosvg` binary under `~/.julia/v0.4/Homebrew/deps`. Could that be the reason for the error?

**Comment by spencerlyon2** [comment]
So I was using `cairsovg` to save figs before, but now I am just using `ImageMagick.jl` as you can see [here](https://github.com/spencerlyon2/PlotlyJS.jl/blob/master/src/api.jl#L54-L90)

And no, that issue is with the javascript interop.

When you try to save the figure, do you keep the plotting window open until that process is totally done? We need to have the window open because we get the base64 encoded plot data via a javascript call to `Plotly.Snapshot.toImage`

**Comment by datafig** [comment]
I have tried it 3 ways now with same error. 

- Using console `julia` REPL. Executing `show(plt); savefig(plt, "test.pdf")`
- Using console `julia` REPL. Executing just `savefig(plt, "test.pdf")` which executes show(plt) 
- Using IJulia notebook()

**Comment by spencerlyon2** [comment]
Hmm. sorry about that.

Can you tell me if there is anything in the javascript console. If you are using the blink backend (REPL) you can do this `PlotlyJS.tools(PlotlyJS.get_window(p))` to open it.

**Comment by datafig** [comment]
So here is the screenshot. I had executed `show(p)` to bring up the plot, followed by `PlotlyJS.tools(PlotlyJS.get_window(p))`. Everything looked nice and dandy.. The error you see in the screenshot is produced right after i execute `savefig(p, "test.pdf")`

![screen shot 2016-01-07 at 11 38 46 am](https://cloud.githubusercontent.com/assets/12907357/12180826/9a9c0d1e-b533-11e5-8a12-04e963d49c1f.png)

**Comment by spencerlyon2** [comment]
Ahh I see.

Yes this makes sense. You will have to `Pkg.checkout("Blink")`. we added some new things to the javascript a few weeks ago and haven't tagged a new release yet. 

I was planning on tagging later today, so if this works for you I will tag a new version and you can `Pkg.free("Blink")`

**Comment by datafig** [comment]
Okay that took care of the problem we were experiencing. Now when I `savefig` i am getting the following errors. And javascript console looks clean... 

```julia
julia> savefig(p, "test.pdf")
ERROR: no decode delegate for this image format `PNG' @ error/blob.c/BlobToImage/355
 in error at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in error at /Users/datafig/.julia/v0.4/ImageMagick/src/libmagickwand.jl:149
 in readimage at /Users/datafig/.julia/v0.4/ImageMagick/src/libmagickwand.jl:240
 in savefig at /Users/datafig/.julia/v0.4/PlotlyJS/src/api.jl:64

julia> savefig(p, "test.svg")
ERROR: no decode delegate for this image format `PNG' @ error/blob.c/BlobToImage/355
 in error at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in error at /Users/datafig/.julia/v0.4/ImageMagick/src/libmagickwand.jl:149
 in readimage at /Users/datafig/.julia/v0.4/ImageMagick/src/libmagickwand.jl:240
 in savefig at /Users/datafig/.julia/v0.4/PlotlyJS/src/api.jl:64

julia> savefig(p, "test.png")
ERROR: no decode delegate for this image format `PNG' @ error/blob.c/BlobToImage/355
 in error at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in error at /Users/datafig/.julia/v0.4/ImageMagick/src/libmagickwand.jl:149
 in readimage at /Users/datafig/.julia/v0.4/ImageMagick/src/libmagickwand.jl:240
 in savefig at /Users/datafig/.julia/v0.4/PlotlyJS/src/api.jl:64
```

**Comment by spencerlyon2** [comment]
Ok cool, getting closer.

So can you do `Pkg.build("ImageMagick")` now. This is not an error I expected to see, but one that I think we can debug

**Comment by datafig** [comment]
no change. same error after `Pkg.build("ImageMagick")`

**Comment by asbisen** [comment]
The problem was identified to be the system installed copy of `imagemagick` through `Homebrew`. Uninstalling imagemagick installed by homebrew using `brew uninstall imagemagick` followed by `Pkg.build("ImageMagick")` resolved the problem. 

I think we can close the issue.

**Comment by spencerlyon2** [comment]
Excellent, thanks for flowing up here
