### ISSUE TITLE
is collapse( ) supposed to work with multiple columns?

### ISSUE THREAD

**Issue by datafig** [spencerlyon2/PlotlyJS.jl#15]
deleted the message as it was posted in wrong forum.

**Comment by spencerlyon2** [comment]
No problem. Good luck with time arrays

**Comment by datafig** [comment]
And thanks a bunch for porting plotly (offline) to Julia. This was much needed.

**Comment by spencerlyon2** [comment]
Thanks, let me know if you find anything that doesn't work or even feel right. There are some rough edges here that I hope to iron out soon so I can publish to Metadata
