### ISSUE TITLE
IJulia notebook export to HTML don't show the plot

### ISSUE THREAD

**Issue by diegozea** [spencerlyon2/PlotlyJS.jl#22]
![exampleexport](https://cloud.githubusercontent.com/assets/2822757/13554427/5684865c-e386-11e5-9876-b39e62c8bbe9.png)

**Comment by spencerlyon2** [comment]
Thanks for reporting. I can't reproduce this. When I export to html the plots show up.

Could you try with a simple example and post the notebook and exported html to a gist so I can take a look.

Thanks

**Comment by diegozea** [comment]
Ok... It works well on my office computer (I will try again at home at night).

```
Julia Version 0.4.1
Commit cbe1bee (2015-11-08 10:33 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
  WORD_SIZE: 64
           Ubuntu 15.04
```

```
 - Blink                         0.3.4
 - IJulia                        1.1.8
 - PlotlyJS                      0.1.0
```

**Comment by diegozea** [comment]
It's working fine now. Thanks!

**Comment by spencerlyon2** [comment]
Great, thanks for reporting
