### ISSUE TITLE
restyle! needs to be fixed... Julia and javascript have different semantics

### ISSUE THREAD

**Issue by spencerlyon2** [spencerlyon2/PlotlyJS.jl#23]
So here's the problem. Suppose you are trying to completely reset `x` and `y` on a trace 1 to be `[1, 2, 3]` and `[4, 5, 2]` respectively.

The natural way to do this would be something like

```julia
restyle!(p, 1, x=[1, 2, 3], y=[4, 5, 2])
```

or

```julia
restyle!(p, 1, Dict(:x=>[1, 2, 3], :y=>[4, 5, 2])
```

This would correctly set the `Plot` object, but on the javascript side the trace would have x and y set to 1 and 4, respectively. 

From the [function reference](https://plot.ly/javascript/plotlyjs-function-reference/) if you want to change an attribute that takes on an array, you need to pass an array of arrays. In Julia we might call them matrices. 

To get the display to update properly you would need to do something like

```julia
restyle!(p, 1, x=[1 2 3]', y=[4 5 2]')
```

This will get translated to the javascript:

```julia
Plotly.restyle(p, {"x": [[1, 2, 3]], "y": [[4, 5, 2]]}, 0)
```

which is exactly what we need to do. However, now the `Plot` object will have a matrix for the x and y attributes and if you try to copy the plot and redisplay it won't work.

Because we had different semantics in Julia and js we are now out of sync

Any ideas how to best resolve this? Which semantics to we enforce?

cc @tbreloff

**Comment by tbreloff** [comment]
I'll take a stab at this and submit a PR if I figure it out.  Thanks for a summary of the problem.

**Comment by spencerlyon2** [comment]
Hey @tbreloff I'm almost done with this actually... let me know before you start on it

**Comment by tbreloff** [comment]
Oh! Ok I'll stop and wait then (I was almost done too!)

**Comment by spencerlyon2** [comment]
I'd love to see your solution as it might be better than mine! Would you mind sharing what you have?
