### ISSUE TITLE
Why is `text` using only the first element of a `Vector{ASCIIString}`?

### ISSUE THREAD

**Issue by diegozea** [spencerlyon2/PlotlyJS.jl#34]
Why is `text` using only the first element of a `Vector{ASCIIString}`?

![image](https://cloud.githubusercontent.com/assets/2822757/14613851/9e1dcbf6-059e-11e6-96d0-e4c85d541a0b.png)

**Comment by spencerlyon2** [comment]
This is expected. 

For functions that share a name with methods from plotly.js, the routines in PlotlyJS.jl also share semantics. This has tradeoffs (like the non-intuitive behavior you see here), but allows us to expose all the plotly.js functionality.


The short answer is that here you want the code:

```julia
PlotlyJS.restyle!(p.0, 1; hoverinfo="text", text=Vector[["a", "b", "c", "d"]])
```

For more info see [this docstring](https://github.com/spencerlyon2/PlotlyJS.jl/blob/7cf9d2c3d3f9dcbd81583e5479018d921dee790e/src/api.jl#L154-L187)

**Comment by diegozea** [comment]
Thanks @spencerlyon2 ! :D
