### ISSUE TITLE
Error when saving as pdf using Electron Display

### ISSUE THREAD

**Issue by ajaypanyala** [spencerlyon2/PlotlyJS.jl#50]
Hi,

I am checking out PlotlyJS.jl and was trying to run a simple test to save a plot as PDF.  Looking at the docs, I tried the following

```
using PlotlyJS
using Blink
p1 = PlotlyJS.Plot(scatter(;y=randn(3)))
PlotlyJS.savefig_imagemagick(sp::ElectronPlot, "test.pdf")
```

**_ERROR: LoadError: UndefVarError: sp not defined_**

How can I fix this ?

Thanks
Ajay

**Comment by cc7768** [comment]
You haven't defined `sp` -- That is the error. What is `sp` supposed to be? Maybe try changing last line to:

```
PlotlyJS.savefig_imagemagick(pl, "test.pdf")
```

**Comment by spencerlyon2** [comment]
Thanks @cc7768. The other issue is that you used the `Plot` function to build your plot instead of the `plot` function  (note the lowercase )

A complete example is

```Julia
using PlotlyJS

p = plot(y=randn(3))
PlotlyJS.savefig_imagemagick(p, "myplot.pdf")
```

**Comment by ajaypanyala** [comment]
Thanks!! But I still see the following error when using the complete example provide

```
ERROR: LoadError: MethodError: `call` has no method matching call(::Type{PlotlyJS.Plot{TT<:PlotlyJS.AbstractTrace}})
Closest candidates are:
  BoundsError()
  BoundsError(, !Matched::Any...)
  DivideError()
  ...
 in plot at /home/panyala/.julia/v0.4/PlotlyJS/src/display.jl:71
```

**Comment by spencerlyon2** [comment]
Hmm I can't quite tell what's going on. Could you please provide all the commands you entered also?

Thanks

**Comment by ajaypanyala** [comment]
It works now. Just a minor syntax error in calling plot. Thanks a lot!

**Comment by spencerlyon2** [comment]
Excellent, thanks for reporting back!

I should point out that using `savefig` to obtain a pdf will result i  a much higher quality image. If that works for you I'd recommend giving it a try.

**Comment by ajaypanyala** [comment]
Thanks for the pointer! I just tried `savefig` and the pdf looks great.
