### ISSUE TITLE
Plots.jl animations

### ISSUE THREAD

**Issue by cstjean** [spencerlyon2/PlotlyJS.jl#53]
This example from the [Plots.jl examples for PlotlyJS](http://plots.readthedocs.io/en/latest/examples/plotlyjs/) doesn't work in a Jupyter notebook:

```julia
p = plot([sin,cos],zeros(0),leg=false)
anim = Animation()
for x = linspace(0,10π,100)
    push!(p,x,Float64[sin(x),cos(x)])
    frame(anim)
end

MethodError: `isactive` has no method matching isactive(::PlotlyJS.JupyterDisplay)
while loading In[31], in expression starting on line 3

 in savefig at /Users/cedric/.julia/v0.4/PlotlyJS/src/savefig.jl:118
 in writemime at /Users/cedric/.julia/v0.4/Plots/src/output.jl:154
...
```

I've seen that `isactive` is defined for Electron, does that mean that it would work under Atom?

**Comment by spencerlyon2** [comment]
Thanks for posting here.

Right now we don't have the ability to write out png, pdf, eps, or jpeg from within the Jupyter notebook (it is a work in progress and quite close, I just need to find time to fix it up). Like you noticed, `isactive ` is defined for `ElectronDisplay`, which means you can use that routine from the Julia REPL. I'm not sure if it will work or not under atom.

**Comment by spencerlyon2** [comment]
The latest release should enable you to save figures from the Jupyter notebook.
