### ISSUE TITLE
Cloud

### ISSUE THREAD

**Issue by matthieugomez** [spencerlyon2/PlotlyJS.jl#55]
Is there a way to save a graph in the cloud? If I dot a plot in PlotlyJS, click on "Save and edit plot in cloud", I end up on a webpage that does not show the plot I've just created (I end up on the default dataset with giraffes orangutans monkeys).

**Comment by tbreloff** [comment]
See Plotly.jl for the cloud api. PlotlyJS.jl is a local package.

**Comment by spencerlyon2** [comment]
Thanks @tbreloff that's exactly right. PlotlyJS.jl is responsible for constructing plots and working with them locally. 

Plotly.jl is a think wrapper around this package that is responsible for intrefacing with the cloud.

**Comment by matthieugomez** [comment]
I get it now. Thanks!

**Comment by malmaud** [comment]
Maybe plotlyjs should address this in its readme

**Comment by spencerlyon2** [comment]
Agreed, I'll add that when I get a chance unless someone else submits a PR
before :)

// Spencer
