### ISSUE TITLE
Does PlotlyJS.jl support unicode now?

### ISSUE THREAD

**Issue by specter119** [spencerlyon2/PlotlyJS.jl#64]
I found it hard to print unicode properly with my laptop, does PlotlyJS.jl support unicode now? if not, when will it support?

**Comment by spencerlyon2** [comment]
Unicode works for me.

Can you provide example code and potentially output (perhaps a screenshot) of when it isn't working?

**Comment by specter119** [comment]
@spencerlyon2 i finally find why i cannot display the unicode, net browser in my country will not set default encoding to unicode(utf-8). all html outputs in utf-8 will display in the proper way.

**Comment by spencerlyon2** [comment]
Ahh ok good to know. Is there any change in this package that I should make to enforce that behavior?

**Comment by specter119** [comment]
Thank you, i will tell you as far as i know.
