### ISSUE TITLE
PlotlyJS doesn't show plots on Julia 0.5 RC3.

### ISSUE THREAD

**Issue by bicycle1885** [spencerlyon2/PlotlyJS.jl#68]
Even the simplest plot doesn't show anything though this may be due to a bug of an upstream.

<img width="824" alt="screen shot 2016-09-05 at 14 30 25" src="https://cloud.githubusercontent.com/assets/905683/18238195/5608d604-7375-11e6-8a79-13c50cec845b.png">

**Comment by spencerlyon2** [comment]
Thanks for reporting.

Things work for me when I use 0.5-rc3. 

Will you please try to open the javascript console on a notebook like that and tell me what you see?

I'm a bit worried that we don't see [this message](https://github.com/spencerlyon2/PlotlyJS.jl/blob/35c159b881949dad51f851799c35006db42d014d/src/displays/ijulia.jl#L62-L63), which indicates that plotly.js has been successfully loaded into the notebook.

**Comment by bicycle1885** [comment]
I reinstalled Jupyter and PlotlyJS.jl and cleaned all cache and settings related to Jupyter, and then I started to see a different error on my machine. This may not be related to PlotlyJS.jl (the message looks like <https://github.com/JuliaLang/ZMQ.jl/issues/73>), but happens just after calling `using PlotlyJS`:

<img width="1386" alt="screen shot 2016-09-06 at 10 40 25" src="https://cloud.githubusercontent.com/assets/905683/18259421/c238ba5c-741e-11e6-95e6-179d145beab6.png">
![screen shot 2016-09-06 at 10 40 22](https://cloud.githubusercontent.com/assets/905683/18259429/cbca8032-741e-11e6-84dc-9793d86c0b3e.png)

---

Copy of the error message shown above:
```
[E 10:40:14.259 NotebookApp] Uncaught exception GET /api/kernels/2425b818-bf17-4bbb-9103-fea05c969007/channels?session_id=C81822BA96DF49328DFBF5B40C5A2FE2 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/2425b818-bf17-4bbb-9103-fea05c969007/channels?session_id=C81822BA96DF49328DFBF5B40C5A2FE2', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Upgrade': 'websocket', 'Accept-Language': 'en-US,en;q=0.8,fr;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Sec-Websocket-Version': '13', 'Host': 'localhost:8888', 'Sec-Websocket-Key': 'aX+9TE9+PiivduvhzxFdZg==', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36', 'Connection': 'Upgrade', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1425, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 296, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File "/usr/local/lib/python2.7/site-packages/jupyter_client/session.py", line 859, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: 'stderr'
```

---

Environment:

```
julia> versioninfo()
Julia Version 0.5.0-rc3+0
Commit e6f843b* (2016-08-22 23:43 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by spencerlyon2** [comment]
Thank you for reporting. 

I think that  here is actually that your new jupyter installation didn't come with `ipywidgets`. Will you install that python library, either through `pip install ipywidgets` or `conda install ipywidgets` -- based on how your python installation is set up?

**Comment by spencerlyon2** [comment]
One more thing, on Julia v0.5-rc3 I had to do `Pkg.checkout("IJulia")`  to get things working in the notebook. I guess there are some inconsistencies between recent version of the Jupyter notebook and the latest release of the IJulia.jl package

**Comment by bicycle1885** [comment]
Thanks a lot! Checking out the master branch of IJulia.jl solved the problem. Sorry for making noise.

**Comment by spencerlyon2** [comment]
No problem, happy it helped!
