### ISSUE TITLE
Error updating package

### ISSUE THREAD

**Issue by cstook** [spencerlyon2/PlotlyJS.jl#70]
Using Windows 10 and julia 0.5.0-rc3-0

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc3+0 (2016-08-22 23:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.update("PlotlyJS")
INFO: Updating METADATA...
INFO: Updating cache of DataFrames...
INFO: Updating cache of DataFrames...
INFO: Computing changes...
INFO: Upgrading BufferedStreams: v0.1.6 => v0.2.0
INFO: Upgrading DataFrames: v0.8.1 => v0.8.2
INFO: Upgrading PlotlyJS: v0.3.3 => v0.4.1
INFO: Rolling back DataFrames from v0.8.2 to v0.8.1
INFO: Rolling back BufferedStreams from v0.2.0 to v0.1.6
ERROR: PlotlyJS: fetch failed to get commit d8a0369f7e, please file an issue at https://github.com/spencerlyon2/PlotlyJS.jl/issues
 in fetch(::Base.LibGit2.GitRepo, ::String, ::String) at .\pkg\write.jl:25
 in #3 at .\pkg\write.jl:53 [inlined]
 in with(::Base.Pkg.Write.##3#4{String,String}, ::Base.LibGit2.GitRepo) at .\libgit2\types.jl:638
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at .\pkg\entry.jl:537
 in update(::String, ::Set{String}) at .\pkg\entry.jl:458
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at .\pkg\dir.jl:31
 in update(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:210

julia>

**Comment by spencerlyon2** [comment]
sorry! Try one more time right no

**Comment by cstook** [comment]
Same error.

**Comment by spencerlyon2** [comment]
Hmm that's strange. because that commit definitely exists on github: https://github.com/spencerlyon2/PlotlyJS.jl/commit/d8a0369f7ec3db300c583a26027078ccb6739529

Maybe try `Pkg.update()` with out the `PlotlyJS` argument to make sure METADATA is ready to go?

**Comment by cstook** [comment]
_
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc3+0 (2016-08-22 23:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of DataFrames...
INFO: Updating cache of DataFrames...
INFO: Updating GLWindow master...
INFO: Updating Reactive master...
INFO: Updating GeometryTypes master...
INFO: Updating GLVisualize master...
INFO: Updating GLAbstraction master...
INFO: Updating FastHenryHelper master...
INFO: Updating LTspice master...
INFO: Computing changes...
INFO: Upgrading BufferedStreams: v0.1.6 => v0.2.0
INFO: Upgrading DataFrames: v0.8.1 => v0.8.2
INFO: Upgrading PlotlyJS: v0.3.3 => v0.4.1
INFO: Rolling back DataFrames from v0.8.2 to v0.8.1
INFO: Rolling back BufferedStreams from v0.2.0 to v0.1.6
ERROR: PlotlyJS: fetch failed to get commit d8a0369f7e, please file an issue at https://github.com/spencerlyon2/PlotlyJS.jl/issues
 in fetch(::Base.LibGit2.GitRepo, ::String, ::String) at .\pkg\write.jl:25
 in #3 at .\pkg\write.jl:53 [inlined]
 in with(::Base.Pkg.Write.##3#4{String,String}, ::Base.LibGit2.GitRepo) at .\libgit2\types.jl:638
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at .\pkg\entry.jl:537
 in update(::String, ::Set{String}) at .\pkg\entry.jl:458
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at .\pkg\dir.jl:31
 in update() at .\pkg\pkg.jl:210

julia>

**Comment by spencerlyon2** [comment]
@tkelman  any idea what's going on here?

**Comment by spencerlyon2** [comment]
@cstook are you on gitter? If so, let's chat over there real quick and get this sorted out

**Comment by tkelman** [comment]
nope. unless there's a typo in later characters of the sha or something? try `git fetch --all` manually from git bash in `Pkg.dir("PlotlyJS")` ? maybe also try moving the `.cache` folder out of the way

**Comment by cstook** [comment]
Chris@Chris-PC MINGW64 ~/.julia/v0.5/PlotlyJS ((v0.3.3))
$ git fetch --all
Fetching origin
remote: Counting objects: 26, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 26 (delta 11), reused 9 (delta 8), pack-reused 4
Unpacking objects: 100% (26/26), done.
From https://github.com/spencerlyon2/PlotlyJS.jl
 * [new branch]      anj/05     -> origin/anj/05
 * [new branch]      gapminder  -> origin/gapminder
   a029419..ded088a  gh-pages   -> origin/gh-pages
   793b361..d8a0369  master     -> origin/master
 * [new branch]      resize_plot -> origin/resize_plot
 * [new branch]      sl/convenience_api -> origin/sl/convenience_api
 * [new branch]      sl/easy_json -> origin/sl/easy_json
   0398f60..362adea  sl/filters -> origin/sl/filters
 * [new branch]      sl/ijulia-comm -> origin/sl/ijulia-comm
error: cannot lock ref 'refs/remotes/origin/sl/js->julia': Unable to create 'C:/                                 Users/Chris/.julia/v0.5/PlotlyJS/.git/refs/remotes/origin/sl/js->julia.lock': In                                 valid argument
 ! [new branch]      sl/js->julia -> origin/sl/js->julia  (unable to update loca                                 l ref)
 * [new branch]      sl/ohlc    -> origin/sl/ohlc
 * [new branch]      sl/restyle-semantics -> origin/sl/restyle-semantics
 * [new branch]      sl/savefig -> origin/sl/savefig
 * [new branch]      sl/styles  -> origin/sl/styles
 * [new branch]      sl/syncplots -> origin/sl/syncplots
 * [new tag]         v0.4.1     -> v0.4.1
error: Could not fetch origin

Chris@Chris-PC MINGW64 ~/.julia/v0.5/PlotlyJS ((v0.3.3))
$

**Comment by cstook** [comment]
How do I move .cache out of the way?

**Comment by spencerlyon2** [comment]
This was my fault. I pushed the tag, but not the commit. Something funny happened with the repo.

Deleting it and then doing `Pkg.add("PlotlyJS")` again fixed the problem.

**Comment by cstook** [comment]
Thank all.
