### ISSUE TITLE
Save and edit plot in cloud

### ISSUE THREAD

**Issue by stephancb** [spencerlyon2/PlotlyJS.jl#75]
The second item in the top menu "save and edit plot in cloud" doesn't really upload the plot generated with PlotlyJS to the Plot.ly server, it only opens their default plot editor. The upload "to the cloud" used to work earlier and I found it quite convenient, as I could make the plot with PlotlyJS locally, which is fast. Once I was satisfied with the plot, I would upload it to Plotly, to share with co-workers, and to do further minor editing interactively in the browser (e.g. when the journal required changes of the axis labels, like a different font).

After signing into plot.ly manually one time from the Electron browser, their plot editor shows that I'm signed in, but the PlotlyJS generated data are still not uploaded.

**Comment by spencerlyon2** [comment]
Hi @stephancb sorry that something seems to have broken.

The recommended way to upload a PlotlyJS.jl figure to plot.ly's cloud is to use the Plotly.jl package.

Here's an example:

```julia
using Plotly  # this will call using PlotlyJS and reexport all the names

p = plot(scatter(y=cumsum(randn(100))), Layout(title="Random walk!"))
post(p)
```

**Comment by stephancb** [comment]
Hi Spencer,

thanks, the recommended way works fine.

**Comment by spencerlyon2** [comment]
Great, thanks for reporting back
