### ISSUE TITLE
Float32 arrays don't plot reliably on 0.5.0

### ISSUE THREAD

**Issue by ssfrr** [spencerlyon2/PlotlyJS.jl#78]
It looks like Julia 0.5 changes the way that single-precision floating-point numbers are displayed in scientific notation. Instead of `3.05e-5` now it's `3.05f-5`. Looks like if any of these show up in the data it hoses the display:

```julia
arr = Float32[-0.00735474, 3.05176f-5, 0.00769043]
plot(scatter(y=arr))
```

causes jupyter to say:

```
Javascript error adding output!
SyntaxError: Invalid or unexpected token
See your browser Javascript console for more details.
```

Related:
https://github.com/JuliaIO/JSON.jl/issues/163
https://github.com/JuliaLang/julia/issues/17720
https://github.com/JuliaLang/julia/pull/18053
https://github.com/JuliaLang/julia/pull/18682

Seems that it should be fixed in master, but hopefully it'll be backported to the next 0.5.x release. This probably shouldn't be worked-around in PlotlyJS, but I wanted to file the issue here in case somebody else came looking for an explanation of the error message.

**Comment by spencerlyon2** [comment]
Thanks for letting is know here -- this is good to know.

Do you think it is an issue that can/should be resolved in JSON.jl?

**Comment by ssfrr** [comment]
OK. the fix PR just got merged into JSON.jl master. Hopefully it will be tagged pretty soon.

**Comment by ssfrr** [comment]
And now it's tagged and merged into METADATA. JSON version 0.7.1 should be good.

**Comment by spencerlyon2** [comment]
Thanks for following up. Next time I tag plotlyjs I'll bump JSON in REQUIRE
