### ISSUE TITLE
handle 2D data matrices in 1D plots e.g. `scatter`

### ISSUE THREAD

**Issue by ssfrr** [spencerlyon2/PlotlyJS.jl#82]
I think the one thing that still bites me regularly is having a 2D data array (sometime Nx1) instead of a 1D vector. would you be into a PR to handle matrices in `scatter`? The simplest thing is just to add a handler for Nx1 or 1xN arrays and treat them like `Vector`s.

The other possible behavior would be to have `scatter(y=data::Matrix)` return `[scatter(y=data[:, 1]), scatter(y=data[:, 2]), …]` so it plots the columns. We could also use `broadcast` to allow `x` to be a `Vector` which is the x-axis for all the columns, or `x` can be a `Matrix` and the columns get matched up.

**Comment by tbreloff** [comment]
I really don't want to stop improvements to PlotlyJS, but @ssfrr: why don't you just use PlotlyJS through Plots?  The idea (I thought) was that those that wanted a more convenient high-level interface to PlotlyJS would do so through Plots, so that we don't reinvent the wheel in a thousand plotting packages.

```julia
using Plots; plotlyjs()
scatter(rand(100,10), m=(0.3,:auto))
```

![tmp](https://cloud.githubusercontent.com/assets/933338/19120964/c8a8e1b0-8af2-11e6-8cff-1f81ee0d088e.png)

**Comment by spencerlyon2** [comment]
Hey @ssfrr, a while back I did add [a few methods](https://github.com/spencerlyon2/PlotlyJS.jl/blob/master/src/convenience_api.jl) to the `plot` function that do things like `plot(x::Matrix, kind=:scatter)` and construct one scatter per column.  That should work for your example. If it does, will you close the issue?

That being said, @tbreloff makes a great point about the bigger issue: how much API should PlotlyJS.jl have above and beyond exposing the plotly.js API? For me the short answer is "not much". I'd still say that Plots.jl is the choice of high-level frontend into PlotlyJS. I don't anticipate this changing. 

There are three main ways I see new functionality/API coming into PlotlyJS:

1. plotly.js changes things, so we change to keep up
2. PlotlyJS.jl maintainers add features that make it easier to generate plotly.js JSON. This will be things like the underscore magic, the` attr` function, and styles. These don't transform data or plot custom types, but rather remove some of the tedium we get when trying to build JSON in Julia
3. We get a PR that adds specific chart type or functionality that plotly.js doesn't have. I'm a bit torn on this one. It will probably be a judgement call on a case by case basis. 

Any thoughts on that plan are welcome!

**Comment by ssfrr** [comment]
@spencerlyon2 my reasoning for adding it to `scatter` et. al is mostly because that's I'm normally using the `plot(scatter(...))` API and working with data that sometimes is 2D and sometimes 1D and I'm not always thinking about which (mostly that's an issue with the Nx1 case, i.e. I don't take vector transposes seriously).

@tbreloff Probably the main reason I've been using the Plotly API directly is that I'm pretty happy with it and haven't felt the need to add a layer of abstraction on top. Sometimes it feels easier to add little things like this as I need them rather than swapping out to a different API. That said, cumulatively those small steps can add up, so perhaps I'm being a little myopic. The other concern is that when I really want to get in and tweak the output I feel like I'd end up needing to learn about the underlying API anyways, so it feels easier to just stay in that API the whole time.

FWIW I'm really impressed with how much work you've put into Plots and how actively you're maintaining it. I'm actually in the process now of switching over some of my pure PlotlyJS.jl plots to reproduce them in Plots.jl to see how it feels, so perhaps this will be a moot point for me soon. :)

**Comment by ssfrr** [comment]
oh, heh. I actually didn't know about the simpler `plot(x, y)` API, so that seems to do what I'm looking for quite nicely. Thanks!
