### ISSUE TITLE
error install :(

### ISSUE THREAD

**Issue by jmarcellopereira** [spencerlyon2/PlotlyJS.jl#83]
Hi, everybody.  when i try install the package occur this error:

==============================[ ERROR: MbedTLS ]===============================

LoadError: failed process: Process(`./cmake_check.sh`, ProcessExited(1)) [1]
while loading /home/jmarcellopereira/.julia/v0.5/MbedTLS/deps/build.jl, in expression starting on line 74

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: MbedTLS had build errors.

 - packages with build errors remain installed in /home/jmarcellopereira/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("MbedTLS")`
 - build a single package by running its `deps/build.jl` script

===============================================================================
INFO: Package database updated

And 
```julia
using Plots
plotlyjs()

# é necessário o ".*" para calcular elemento por elemento do vetor x
x = 0 : 0.5 : 3*pi
fx(x) = sin(x).*x
gx(x) = cos(x).*x

plot( x , fx(x), label = "sin")
plot!(x , gx(x), label = "cos", size = (400,300)) 
```
occur:
INFO: Precompiling module PlotlyJS.
ERROR: LoadError: MbedTLS not properly installed. Please run Pkg.build("MbedTLS")
 in error(::String) at ./error.jl:21
 in include_from_node1(::String) at ./loading.jl:488
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/jmarcellopereira/.julia/v0.5/MbedTLS/src/MbedTLS.jl, in expression starting on line 43
ERROR: LoadError: Failed to precompile MbedTLS to /home/jmarcellopereira/.julia/lib/v0.5/MbedTLS.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:393
 in include_from_node1(::String) at ./loading.jl:488
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/jmarcellopereira/.julia/v0.5/HttpServer/src/HttpServer.jl, in expression starting on line 10
ERROR: LoadError: LoadError: Failed to precompile HttpServer to /home/jmarcellopereira/.julia/lib/v0.5/HttpServer.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:393
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/jmarcellopereira/.julia/v0.5/Mux/src/server.jl, in expression starting on line 1
while loading /home/jmarcellopereira/.julia/v0.5/Mux/src/Mux.jl, in expression starting on line 22
ERROR: LoadError: LoadError: Failed to precompile Mux to /home/jmarcellopereira/.julia/lib/v0.5/Mux.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:393
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/jmarcellopereira/.julia/v0.5/Blink/src/content/content.jl, in expression starting on line 1
while loading /home/jmarcellopereira/.julia/v0.5/Blink/src/Blink.jl, in expression starting on line 9

ERROR: LoadError: Failed to precompile Blink to /home/jmarcellopereira/.julia/lib/v0.5/Blink.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:393
 in include_from_node1(::String) at ./loading.jl:488
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/jmarcellopereira/.julia/v0.5/PlotlyJS/src/PlotlyJS.jl, in expression starting on line 7
WARNING: Couldn't initialize plotlyjs.  (might need to install it?)
INFO: To do a standard install of plotlyjs, copy and run this:

**Comment by tbreloff** [comment]
For some reason you need cmake installed.  Install it, then `Pkg.build("MbedTLS")`?

**Comment by jmarcellopereira** [comment]
Hi tbrloff
I did and:
INFO: Building MbedTLS

cmake command not found. installing cmake is required for building from source.

===============================[ ERROR: MbedTLS ]===============================

LoadError: failed process: Process(`./cmake_check.sh`, ProcessExited(1)) [1]
while loading /home/jmarcellopereira/.julia/v0.5/MbedTLS/deps/build.jl, in expression starting on line 74

===============================================================================
================================[ BUILD ERRORS ]================================

WARNING: MbedTLS had build errors.

 - packages with build errors remain installed in /home/jmarcellopereira/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("MbedTLS")`
 - build a single package by running its `deps/build.jl` script

================================================================================
strange this error cmake

**Comment by jmarcellopereira** [comment]
Hi tbreloff
ok, i will try. Thanks ;)

**Comment by jmarcellopereira** [comment]
Hi  tbreloff,now it's working :) thanks for this.

**Comment by BryanARivera** [comment]
This should be on the README.  Just ran into it myself.

**Comment by spencerlyon2** [comment]
@BryanARivera done
