### ISSUE TITLE
Aspect ratio for 2D plot

### ISSUE THREAD

**Issue by ghuba** [spencerlyon2/PlotlyJS.jl#85]
Is there a way to set the aspect ratio for 2D plots? This can be very useful to plot a unit disc for example (and many other things).

From the documentation there is an option in 3D but not 2D. Here is what I tried:

```
using PlotlyJS
t = linspace(0,2*pi,128)
tr = scatter(x=cos(t),y=sin(t),mode="lines")
# tr = scatter3d(x=cos(t),y=sin(t),z=t,mode="lines")
# lay = Layout(scene=attr(aspectratio=attr(x=1,y=1,z=5)))
lay = Layout(scene=attr(aspectmode="data"))
plot([tr],lay)
```

**Comment by spencerlyon2** [comment]
Does setting the Layout's width and height to be the same work (e.g. `lay = Layout(width=500, height=500)`)?

**Comment by ghuba** [comment]
Close enough. I found that this option makes the circle roughly round:
```
lay = Layout(width=450,height=500)
```
Thanks.

**Comment by tbreloff** [comment]
Just in case you didn't know, you can do this in Plots with the
'aspect_ratio' attribute.

**Comment by ghuba** [comment]
That's not the case in my version but perhaps you have pushed a recent update? I have Julia 0.5.0 with 
```
 - PlotlyJS                      0.5.0
 - Plots                         0.9.3
 - PyPlot                        2.2.4
```

pyplot() works but not plotlyjs().

```
pyplot()
# plotlyjs()
θ = linspace(0,2*pi,100)
plot(cos(θ), sin(θ), aspect_ratio=:equal)
title!("A ball using the 2-norm")
```

**Comment by tbreloff** [comment]
Yeah I need to tag Plots.
