### ISSUE TITLE
Add nteract support for JupyterPlot

### ISSUE THREAD

**Issue by jackparmer** [spencerlyon2/PlotlyJS.jl#90]
`JupyterPlot` currently doesn't work out-of-the-box inside [nteract](https://nteract.io/)

There's a discussion for Plotly's Python interface that `JupyterPlot` can probably draft behind:

https://github.com/plotly/plotly.py/pull/562

**Comment by rgbkrk** [comment]
For nteract, any Jupyter kernel that returns [Plotly's JSON Chart Schema](http://help.plot.ly/json-chart-schema/) with mimetype `application/vnd.plotly.v1+json` can go straight from a dict/object/map to render:

![screen shot 2016-10-23 at 8 21 53 pm](https://cloud.githubusercontent.com/assets/836375/19632727/5d7ef670-995e-11e6-85e4-b6150b1ba501.png)

**Comment by spencerlyon2** [comment]
Thanks for opening this @jackparmer.

Sorry for the delay in responding

I would love to get nteract support for this package.

@rgbkrk thanks for the example. It seems like it should be pretty straightforward. If I have any issues do you mind if I ping you for pointers?

**Comment by spencerlyon2** [comment]
Yep, it was easy!! Added in d9f881d9fc3084faef68325f2251d58ca6b2a397





<img width="1440" alt="screen shot 2016-10-26 at 11 50 40 pm" src="https://cloud.githubusercontent.com/assets/1001948/19753951/0602d968-9bd7-11e6-8789-60c71ea33a35.png">
