### ISSUE TITLE
Stacked subplots, more than 2 yaxis

### ISSUE THREAD

**Issue by stephancb** [spencerlyon2/PlotlyJS.jl#96]
The third "yaxis3" is not added to the layout?:
```
julia> bigfont3=Layout(font_size=22, yaxis=attr(domain=[0, 0.33]), legend=attr(traceorder="reversed"), yaxis2=attr(domain=[0.33, 0.66], yaxis3=attr(domain=[0.67, 1])))
layout with fields font, legend, margin, yaxis, and yaxis2

```
and the resulting plot is correspondingly not as intended, the third axis covering all space.

Thanks,
Stephan

**Comment by stephancb** [comment]
Sorry, was just an error with the brackets.

**Comment by spencerlyon2** [comment]
No problem, I'm glad you were able to figure it out!

I also want to point out that there is a more convenient notation for making regular grids of subplots (see the docs [here](http://spencerlyon.com/PlotlyJS.jl/manipulating_plots/#subplots)).

**Comment by stephancb** [comment]
Thanks. My subplots share the same x axis, I need relatively large fonts for the axis tick- and textlabels, and cannot afford to waste space by repeating the x axis incl. labels at each subplot. Therefore I had not used the convenient notation.

**Comment by spencerlyon2** [comment]
No problem -- sounds like you have a good handle on it!
