### ISSUE TITLE
clims in heatmap not supported?

### ISSUE THREAD

**Issue by BoundaryValueProblems** [spencerlyon2/PlotlyJS.jl#99]
The attribute/keyword ```clims``` in ```heatmap``` using ```PlotlyJS``` as an backend for ```Plots.jl``` does not work.
On the other hand, it works if I use ```PyPlot``` as an backend for ```Plots.jl```.
I'm wondering why ```clims``` does not work under ```PlotlyJS```. Is it not currently supported? Will it eventually be supported? Is there any simple workaround?
Thanks,
BVPs

**Comment by spencerlyon2** [comment]
Hi @BoundaryValueProblems I'm a little confused. Are you saying that when you use the plotlyjs backend for Plots.jl the clims argument doesn't work? If so, @tbreloff is this a known issue in Plots.jl

On the other hand, if you are trying to build a heat map with PlotlyJS.jl by itself (not through Plots.jl) you need to set the `colorscale` attribute not `clims`. The [documentation](https://plot.ly/javascript/reference/#heatmap-colorscale) says:

>colorscale (colorscale) 
The colorscale must be an array containing arrays mapping a normalized value to an rgb, rgba, hex, hsl, hsv, or named color string. At minimum, a mapping for the lowest (0) and highest (1) values are required. For example, `[[0, 'rgb(0,0,255)', [1, 'rgb(255,0,0)']]`. To control the bounds of the colorscale in color space, use `marker.cmin` and `marker.cmax`. Alternatively, `colorscale` may be a palette name string of the following list: Greys, YlGnBu, Greens, YlOrRd, Bluered, RdBu, Reds, Blues, Picnic, Rainbow, Portland, Jet, Hot, Blackbody, Earth, Electric, Viridis

**Comment by BoundaryValueProblems** [comment]
Thanks, Spencer.
Yes, ```clims``` argument does not work when I use the ```plotlyjs``` backend for ```Plots.jl```. For example,
```julia
heatmap(randn(100,100), clims=(-0.1, 0.1), aspect_ratio=1)
```
does not work. But if I use the ```pyplot``` backend, then the same command is effective and works. So, should I post this to ```Plots.jl``` issues?
Best,
BVPs

**Comment by tbreloff** [comment]
This should be a Plots issue, though it might already be filed.
